apiVersion: v1 
kind: ReplicationController
metadata:
    name: rc-pod
    labels: 
      app: rc-pod
spec: 
  selector:
    app: rc-pod
  replicas: 2
  template:
     metadata:
       labels:
         app: rc-pod
     spec:
        containers:
          - name: rc-container
            image: httpd:latest
            ports:
             - containerPort: 80             